api/urls.py
from django.urls import path
from .views import ProjectView

urlpatterns = [
    path('project', ProjectView.as_view())
]

projectmanager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [    
    path('', include("accounts.urls")),
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),   
    path('projects/', include('testfront.urls')),
]

testfront/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.mainpage, name="projectall"),
    path('new', views.newproject, name="newproject"),
    path('<project_ord>/', views.projectview, name="project"),
    path('edit/<project_code>', views.projectedit, name="projectedit"),
    path('delete/<project_code>', views.projectdel, name="projectdel"),
    path('delete_log', views.deletelog, name="deletelog"),
]

api/models.py
from django.db import models
import string
import random
import pytz
from django.core.exceptions import ValidationError
from datetime import datetime, timedelta
from django.core.validators import RegexValidator
from django.contrib.auth.models import User
from django.urls import reverse

# Generate random slug
def generate_unique_code():
    length = 6

    while True:
        code = ''.join(random.choices(string.ascii_uppercase, k=length))
        if Project.objects.filter(code=code).count() == 0:
            break

    return code

# Create your models here.
class Project(models.Model):
    STATUS_CHOICES = [
     ("Headsup","Headsup"),
     ("Programming","Programming"),
     ("Changes","Changes"),
     ("Live", "Live"),
     ("LiveChange", "Live Changes"),
     ("Paused", "Paused"),
     ("Closed", "Closed")
    ]
    REGION_CHOICES = [
      ("APAC","APAC"),
      ("EMEA","EMEA"),
      ("NA","NA")
    ]
    PLATFORM_CHOICES = [
      ("Decipher", "Decipher"),
      ("CMIX","CMIX"),
      ("Confirmit","Confirmit")
    ]    
    # eta check
    __original_eta = None

    code = models.SlugField(max_length=8, default=generate_unique_code, unique=True)
    ord = models.CharField(max_length=15, unique=True, validators=[RegexValidator(regex="^ORD-[0-9]{6}-[0-9A-Z]{4}$", message="Please enter the ORD in ORD-XXXXX-XXXX format.")])
    project_name = models.CharField(max_length=200)
    status = models.CharField(max_length=20, default="Headsup", choices=STATUS_CHOICES)
    created_date = models.DateField(auto_now_add=True)
    region = models.CharField(max_length=10, blank=True, choices=REGION_CHOICES)
    pid = models.CharField(max_length=20, blank=True)
    platform = models.CharField(max_length=15, default="Decipher", choices=PLATFORM_CHOICES)
    eta = models.DateTimeField(null=True,blank=True)
    details = models.TextField(max_length=255, blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE,null=True)
  
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_eta = self.eta

    # validation to check ETA
    def clean(self):
      if self.eta is not None:
        data = datetime.strptime(str(self.eta), "%Y-%m-%d %H:%M:%S%z")
        nowdata = datetime.now() + timedelta(hours=1)
        now = pytz.utc.localize(nowdata)

        if (now > data):
            if self.__original_eta is not None:
              if self.eta != self.__original_eta:
                raise ValidationError({
                  "eta": "If you wish to change the ETA, please enter an ETA at least an hour from now"
                })
            else:
              raise ValidationError({
                 "eta": "Please enter an ETA at least an hour from today"
              })    

    def __str__(self):
        return f"{self.ord} - {self.project_name}"
    
    def get_absolute_url(self):        
        return reverse("project", args=[self.ord])    

class ProjectLog(models.Model):
   UPDATE_CHOICES = [
      ("update","Update only"),
      ("scripting","Started Scripting"),
      ("testlinksent","Test Link Sent"),
      ("settolive","Set to Live"),
      ("settolivechange","Change to Live Changes"),
      ("paused","Paused"),
      ("toclosed","Set to Closed"),
      ("reopened","Re-open Project"),
      ("created","Project created"),
      ("edited","Project details edited")
   ]

   HEADER_CHOICES = [
      ("update","posted an update"),
      ("scripting","started scripting the project"),
      ("testlinksent","sent the test link(s)"),
      ("settolive","launched the study"),
      ("settolivechange","made some live changes"),
      ("paused","paused the study"),
      ("toclosed","closed the study"),
      ("reopened","reopened the study"),
      ("created","created this project"),
      ("edited","edited some details for this project")      
   ]

   project = models.ForeignKey(Project, on_delete=models.CASCADE, to_field="code")
   creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
   log_header = models.CharField(max_length=255, default="update", choices=HEADER_CHOICES)
   message = models.TextField(max_length=255, blank=True, null=True)   
   update_type = models.CharField(max_length=20, default="update", choices=UPDATE_CHOICES)
   created_date = models.DateTimeField(auto_now_add=True)

testfront/models.py
from django.db import models

# Create your models here.

testfront/forms.py
from django import forms
from api.models import Project, ProjectLog
from datetime import datetime, timedelta

class ProjectForm(forms.ModelForm):
    class Meta:
       form_controlClass = {"class": "form-control"}
       form_selectClass = {"class": "form-select"}
       eta = datetime.today() + timedelta(hours=1)
       etastr = eta.strftime("%Y-%m-%dT%H:00")

       model = Project
       fields = "__all__"
       exclude = ["code","creator","status"]
       widgets = {
           "ord": forms.TextInput(attrs={**form_controlClass, "placeholder":"ORD-XXXXXX-XXXX"}),
           "project_name": forms.TextInput(attrs=form_controlClass),
           "region": forms.Select(attrs=form_selectClass),
           "pid": forms.TextInput(attrs={**form_controlClass, "placeholder":"Example, for Decipher projects, ID is 53c/201104"}),
           "platform": forms.Select(attrs=form_selectClass),
           "hours": forms.TextInput(attrs=form_controlClass),
           "eta": forms.TextInput(attrs={**form_controlClass, "type":"datetime-local", "min":etastr}),
           "details": forms.Textarea(attrs=form_controlClass)
       }
    
    def __init__(self, *args, **kwargs):
        method = kwargs.pop("method", "add")
        super().__init__(*args,**kwargs)
        if (method == "edit"):
            self.fields["ord"].disabled = True

class ProjectLogForm(forms.ModelForm):
    class Meta:
       model = ProjectLog
       fields = ["id","message", "update_type"]
       widgets = {
            "message": forms.Textarea(attrs={"class": "form-control", "placeholder": "Enter your update here", "rows":"5"}),
            "update_type": forms.Select(attrs={"class":"form-select form-select-sm"})
        }

    def __init__(self, *args, **kwargs):
        project = kwargs.pop("project", None)        
        super().__init__(*args, **kwargs)
        if isinstance(project, Project):
            if project.status in ["Headsup"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ('scripting', 'Started Scripting'),
                    ("toclosed","Set to Closed")
                ]
            elif project.status in ["Programming"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ("testlinksent","Test Link Sent"),                    
                    ("settolive","Set to Live"),
                    ("paused","Paused"),
                    ("toclosed","Set to Closed")
                ]
            elif project.status in ["Changes"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ("settolive","Set to Live"),
                    ("paused","Paused"),
                    ("toclosed","Set to Closed")
                ]
            elif project.status in ["Live"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ("settolivechange","Change to Live Changes"),
                    ("paused","Paused"),
                    ("toclosed","Set to Closed")
                ]
            elif project.status in ["LiveChange"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ("settolive","Set to Live"),
                    ("paused","Paused"),
                    ("toclosed","Set to Closed")
                ]
            elif project.status in ["Paused"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ("settolive","Set to Live"),
                    ("toclosed","Set to Closed")
                ]
            elif project.status in ["Closed"]:
                self.fields["update_type"].choices = [
                    ('update', 'Update only'),
                    ("reopened","Re-open Project"),
                ]

testfront/views.py
from django.shortcuts import render, redirect
from api.models import Project, ProjectLog
from .forms import ProjectForm, ProjectLogForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
import re
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse, HttpResponseForbidden
from django.contrib.auth.models import User

# search project setup
def search_project(search_key):
    searchTxt = search_key.strip()
    if searchTxt.strip() == "":
        projects_list = Project.objects.all()
    else:
        # check if search matches ord
        try:
            if re.search("^ORD-[0-9]{6}-[0-9A-Z]{4}$", searchTxt):
                projects_list = Project.objects.get(ord=searchTxt)
            else:
                projects_list = Project.objects.filter(ord__icontains=searchTxt) | Project.objects.filter(project_name__icontains=searchTxt)
        except Exception:
            projects_list = [] # return empty if not found
    
    return projects_list

# paginator setup
def paginator_setup(query_list, page_get, item_per_page=15):
    project_pages = Paginator(query_list.order_by("-created_date"), item_per_page)
    page_num = page_get

    if page_num >= project_pages.num_pages:
        page_num = project_pages.num_pages
    
    min_page = page_num - 2
    if min_page <= 1:
        min_page = 1
    max_page = min_page + 4
    if max_page >= project_pages.num_pages:
        max_page = project_pages.num_pages

    project_page = project_pages.page(page_num)
    
    prev_page = 1
    if project_page.has_previous():
        prev_page = page_num - 1
    next_page = project_pages.num_pages
    if project_page.has_next():
        next_page = page_num + 1

    return {
        "items": project_page.object_list,
        "pages": range(min_page, max_page+1),
        "last": project_pages.num_pages,
        "current": project_page.number,
        "showPrev": project_page.has_previous(),
        "showNext": project_page.has_next(),
        "prev_page": prev_page,
        "next_page": next_page
    }

# add to log when adding/editing project
def addtolog(projectObj: Project, user: User, updates=[]):
    logCheck = ProjectLog.objects.filter(project=projectObj).count()
    if logCheck > 0:
        messageStr = "The following details are edited:\n\n"
        for item in updates:            
            messageStr += f"{item['key']}: {item['value']}\n"
        log = ProjectLog(
            project=projectObj,
            creator=user,
            update_type="edited",
            log_header="edited",
            message=messageStr
        )
    else:
        log = ProjectLog(
            project=projectObj,
            creator=user,
            update_type="created",
            log_header="created"
        )
    
    log.save()
        
# Create your views here.
@login_required
def mainpage(request):
    if "search" in request.GET:
        projects_list = search_project(request.GET["search"])
    else:
        projects_list = Project.objects.all()

    page_num = 1
    if "page" in request.GET:
        if str(request.GET["page"]).isdigit():
            page_num = int(request.GET["page"])

    paginator_result = paginator_setup(projects_list, page_num)        
    return render(request, "testfront/projectlist.html", paginator_result)

@login_required
@permission_required("api.view_project",raise_exception=True)
def projectview(request, project_ord):
    project = get_object_or_404(Project, ord=project_ord)
    creator = f"{project.creator.first_name} {project.creator.last_name}"
    logs = ProjectLog.objects.filter(project=project).order_by("-created_date")

    if request.method == "GET":
        logform = ProjectLogForm(project=project)
    else:
        logform = ProjectLogForm(request.POST)
        if logform.is_valid():
            log = logform.save(commit=False)
            log.log_header = log.update_type
            log.project = project
            log.creator = request.user
            log.save()

            # edit project status based on status
            if log.update_type == "scripting":
                project.status = "Programming"
            elif log.update_type == "testlinksent":
                project.status = "Changes"
            elif log.update_type == "settolive":
                project.status = "Live"
            elif log.update_type == "settolivechange":
                project.status = "LiveChange"
            elif log.update_type == "paused":
                project.status = "Paused"
            elif log.update_type == "toclosed":
                project.status = "Closed"
            elif log.update_type == "reopened":
                project.status = "Live"

            project.save()
            logform = ProjectLogForm(project=project)
            messages.success(request, "Log added succesfully")

    
    page_num = 1
    if "page" in request.GET:
        if str(request.GET["page"]).isdigit():
            page_num = int(request.GET["page"])
    
    paginator_result = paginator_setup(logs, page_num, 10)
    return render(request, "testfront/project.html", {
        **paginator_result,
        "project": project,
        "creator": creator,
        "form": logform
    })

@login_required
@permission_required("api.add_project",raise_exception=True)
def newproject(request):
    if request.method == "GET":            
       form = ProjectForm(initial={'creator':request.user.username})           
       return render(request, "testfront/formproject.html", {
           "form": form,           
           "formText": "Add"
       })
    else:
       form = ProjectForm(request.POST)
       if form.is_valid():
           project = form.save(commit=False)
           project.creator = request.user
           project.save()

           addtolog(project, request.user)
           messages.success(request, "Project added succesfully")
           return redirect("projectall")
       else:
           print("Form is invalid")
           return render(request, "testfront/formproject.html", {
            "form": form,
            "formText": "Add"
           })

@login_required
def projectedit(request, project_code):
    editproj = get_object_or_404(Project, code=project_code)
    if (editproj.creator != request.user and not request.user.has_perm("api.change_project")):
        return HttpResponseForbidden("Access denied")
    
    if request.method == "GET":
        username = f"{editproj.creator.first_name} {editproj.creator.last_name}"
        form = ProjectForm(instance = editproj, method="edit")
        return render(request, "testfront/formproject.html", {
            "form": form,
            "formText": "Edit",
            "username": username
        })
    else:
        form = ProjectForm(request.POST, instance=editproj, method="edit")
        if form.is_valid():
            updates = []
            if form.has_changed():
                for field in form.changed_data:
                    updates.append({
                        "key": field,
                        "value": form.cleaned_data[field]
                    })
            project = form.save()

            addtolog(project, request.user, updates)
            messages.success(request, "Project edited successfully")
            return redirect("projectall")
        else:
            print("Form is invalid")
            return render(request, "testfront/formproject.html", {
            "form": form,
            "formText": "Edit"
           })

@login_required
def projectdel(request, project_code):    
    project = get_object_or_404(Project, code=project_code)
    if (project.creator != request.user and not request.user.has_perm("api.change_project")):
        return HttpResponseForbidden("Access denied")

    if (request.method == "GET"):
        return render(request, "testfront/formdelete.html", {
            "project": project
        })
    else:
        project.delete()
        return redirect("projectall")
    
@login_required
def deletelog(request):    
    if request.method == "POST":
        logid = request.POST['logid']
        log = ProjectLog.objects.get(id=logid)
        if log.update_type == "update":
            project = log.project
            log.delete()
        else:
            return HttpResponseForbidden("Only update type logs are allowed")

        return redirect(project)

testfront/templates/testfront/formdelete.html
{% extends "base.html" %}
{% load static %}

{% block title %} {{formText}} Project - Project Manager {%endblock %}
{% block css %} {% static "css/index.css" %} {% endblock %}

{% block body %}
<h2>Delete Project</h2>

<form class="my-4" method="POST">
    {% csrf_token %}
    <h5>Are you sure you want to delete {{project.ord}} - {{project.project_name}}?</h5>
    <h6>This action will not be undone.</h6>

    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a role="button" href="{% url "projectall" %}" class="btn btn-secondary">No</a>
</form>


{% endblock %}

testfront/templates/testfront/project.html
{% extends "base.html" %}
{% load static %} 

{% block title %} {{project.ord}} - {{project.project_name}} Project Manager {% endblock %} 
{% block css %} {% static "css/index.css" %} {% endblock %} 
{% block body %}
<header>
    <h4><span class="text-truncate">{{project.ord}} - {{project.project_name}}</span> <span class="badge rounded-pill 
        {% if project.status == "Headsup" %} text-bg-info {% endif %}
        {% if project.status == "Programming" %} text-bg-primary {% endif %}
        {% if project.status == "Changes" or project.status == "LiveChange" %} text-bg-warning {% endif %}
        {% if project.status == "Live" %} text-bg-success {% endif %}
        {% if project.status == "Paused" %} text-bg-secondary {% endif %}
        {% if project.status == "Closed" %} text-bg-danger {% endif %}
      ">{{project.get_status_display|upper}}</span></h4>
</header>

<hr/>

<main class="container">
<div class="d-lg-flex justify-content-between">
    <div class="col-lg-3 p-3 rounded shadow">
        <h5>Summary</h5>
        <hr/>
        <div class="row mt-1">
            <div class="col-sm-4 fw-bold">
                Main SP
            </div>
            <div class="col-sm-8">
                {{creator}}
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-sm-4 fw-bold">
                Region
            </div>
            <div class="col-sm-8">
                {{project.region}}
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-sm-4 fw-bold">
                Platform
            </div>
            <div class="col-sm-8">
                {{project.platform}}
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-sm-4 fw-bold">
                ETA
            </div>
            <div class="col-sm-8">
                {{project.eta}}
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-sm-12">
                <a role="button" class="btn btn-success d-block {% if project.creator != user and not perms.api.change_project %} disabled {% endif %}" href="{% url "projectedit" project.code %}">Edit Project</a>
            </div>
        </div>
           
    </div>
    <form class="col-lg-8 rounded shadow p-3 mt-lg-0 mt-sm-3 mb-3" method="POST">
        {% csrf_token %}
       <h5>Make an update</h5>
       <hr/>
       {{form.message}}
       {% if form.message.errors %}
       <div class="alert alert-danger mt-2" role="alert">
         <ul class="list-unstyled my-0">
           {% for error in form.message.errors %}
           <li>{{error}}</li>
           {% endfor %}
         </ul>
       </div>
       {% endif %}  
       <div class="d-flex mt-2 justify-content-between align-items-center">
        <div>{{ form.update_type }}</div>
        <div class="text-end">
            <button type="submit" class="btn btn-primary">Post Update</button>
        </div>
       </div>
    </form>
</div>
<div class="container mt-4">
    <div class="d-flex mb-4 justify-content-between">
        <h4>Updates</h4>
        {% if pages|length > 1 %}
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            <li class="page-item {% if current == 1  %}disabled{%endif%}">
              <a class="page-link" href="{% url "projectall" %}">First</a>
            </li>
            {% if showPrev %} <li class="page-item"><a class="page-link" href="?page={{prev_page}}">Previous</a></li> {% endif %}
            {% for page in pages %}
            <li class="page-item"><a class="page-link {% if current == page %} active {% endif %}" href="?page={{page}}">{{page}}</a></li>
            {% endfor %}
            {% if showNext %} <li class="page-item"><a class="page-link" href="?page={{next_page}}">Next</a></li> {% endif %}
            <li class="page-item">
              <a class="page-link {% if current == last %}disabled{%endif%}" href="?page={{last}}">Last</a>
            </li>
          </ul>
        </nav>
        {% endif %}        
    </div>

    {% if messages %}
    <div class="alert alert-success mb-4" role="alert">      
    {% for message in messages %}
        {{ message }}
    {% endfor %}
    {% endif %}
    </div>
    {% for log in items %}
    <div class="card 
    
    {% if log.update_type == "update" %} text-bg-secondary {% endif %}
    {% if log.update_type == "scripting" %} text-bg-success {% endif %}
    {% if log.update_type == "testlinksent" or log.update_type == "settolivechange" %} text-bg-warning {% endif %}
    {% if log.update_type == "settolive" or log.update_type == "toclosed" %} text-bg-danger {% endif %}
    {% if log.update_type == "paused" or log.update_type == "reopened" or log.update_type == "created" or log.update_type == "edited" %} text-bg-primary {% endif %}

    mb-4">
        <div class="card-header d-flex justify-content-between">
            <div>{{log.get_update_type_display}}</div>
            {% if log.update_type == "update" %}
               {% if log.creator == user or perms.api.delete_projectlog%}
                <form action="{% url "deletelog" %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="logid" value="{{log.id}}" />
                    <button type="submit" class="btn-close" aria-label="Close"></button>
                </form>
                {% endif %}
            {% endif %}
          </div>
        <div class="card-body">            
          <h5 class="card-title">{{log.creator.first_name}} {{log.creator.last_name}} {{ log.get_log_header_display }}</h5>
          {% if log.message %} 
            <p class="card-text">
            {{log.message|linebreaks}}
            </p>
          {% endif %}
        </div>
        <div class="card-footer">
            {{log.created_date}}
        </div>
    </div>  
    {% empty %}
    <h6 class="text-center">Please add updates to this project</h6>
    {% endfor %}
</div>
</main>
{% endblock %}

testfront/templates/testfront/projectlist.html
{% extends "base.html" %}
{% load static %}

{% block title %} Project Manager {% endblock %}
{% block css %} {% static "css/index.css" %} {% endblock %}

{% block body %}

      <form class="row">
        <div class="col-10">
          <div class="input-group">
          <input type="text" class="form-control" name="search" minlength="3" placeholder="Search by ORD or project name" aria-label="Search Project" aria-describedby="button-search">
          <button class="btn btn-outline-secondary" type="submit" id="button-search">Search</button>
          </div>
        </div>
        <div class="col-2 d-grid">
          <a role="button" class="btn btn-success" href="{% url "newproject" %}">
            + Add Project
          </a>
        </div>
      </form>
      {% if messages %}

      <div class="alert alert-success mt-2" role="alert">      
        {% for message in messages %}
          {{ message }}
        {% endfor %}
      </div>
      {% endif %}
      <hr class="border-2 border-black opacity-100" />
      {% if items|length > 0 %}
      <table class="table">
        <thead>
          <tr>
            <th scope="col">&nbsp;</th>
            <th scope="col">Project</th>
            <th scope="col text-center">Status</th>
            <th scope="col text-center">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for project in items %}
          <tr>
            <th class="align-middle" scope="row"><input class="form-check-input" type="checkbox" value=""></th>
            <td class="align-middle"><a href="{{ project.get_absolute_url }}" class="fw-bold text-decoration-none">{{project.ord}} - {{project.project_name}}</a></td>
            <td class="align-middle"><span class="badge rounded-pill 
              {% if project.status == "Headsup" %} text-bg-info {% endif %}
              {% if project.status == "Programming" %} text-bg-primary {% endif %}
              {% if project.status == "Changes" or project.status == "LiveChange" %} text-bg-warning {% endif %}
              {% if project.status == "Live" %} text-bg-success {% endif %}
              {% if project.status == "Paused" %} text-bg-secondary {% endif %}
              {% if project.status == "Closed" %} text-bg-danger {% endif %}
            ">{{project.get_status_display|upper}}</span></td>
            
            <td class="align-middle">
              <div class="dropdown">
                <button class="px-3 py-1 btn btn-outline-secondary btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                  ...
                </button>
                <ul class="dropdown-menu">                  
                    <li><a class="dropdown-item {% if project.creator != user and not perms.api.change_project %} disabled {% endif %}" href="{% url "projectedit" project.code %}">Edit Project</a></li>
                    <li><a class="dropdown-item {% if project.creator != user and not perms.api.delete_project %} disabled {% endif %}" href="{% url "projectdel" project.code %}">Delete Project</a></li>
                </ul>
              </div>
          </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>

      {% if pages|length > 1 %}
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          <li class="page-item {% if current == 1  %}disabled{%endif%}">
            <a class="page-link" href="{% url "projectall" %}">First</a>
          </li>
          {% if showPrev %} <li class="page-item"><a class="page-link" href="?page={{prev_page}}">Previous</a></li> {% endif %}
          {% for page in pages %}
          <li class="page-item"><a class="page-link {% if current == page %} active {% endif %}" href="?page={{page}}">{{page}}</a></li>
          {% endfor %}
          {% if showNext %} <li class="page-item"><a class="page-link" href="?page={{next_page}}">Next</a></li> {% endif %}
          <li class="page-item">
            <a class="page-link {% if current == last %}disabled{%endif%}" href="?page={{last}}">Last</a>
          </li>
        </ul>
      </nav>
      {% endif %}
      {% endif %}

      {% if items|length == 0 %}
      <div class="text-center">
        <h1>No projects</h1>
        <p>Refine your search, or click the "Add Project" button</p>
      </div>
      {% endif %}
{% endblock %}